// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qawxpxhuaelcsiyienia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhd3hweGh1YWVsY3NpeWllbmlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5OTI4ODIsImV4cCI6MjA2MzU2ODg4Mn0.MYz3WetteKJuaIJmjcrmJQMAKK-c8b7gV3yNBkyuUXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);